### ISSUE TITLE
CUDA error cudaErrorLaunchFailure 

### ISSUE THREAD

**Issue by maciejmatuszak** [yunchih/ORB-SLAM2-GPU2016-final#1]
Hi,
I am trying to replicate your results with CUDA enabled ORB_SLAM2 but I am getting the following error:

`CUDA error at /data/git/miner-tx1/catkin_ws/src/orb_slam_gpu/src/cuda/Fast_gpu.cu:507 code=4(cudaErrorLaunchFailure) "cudaMemcpyAsync(_keypoints, keypoints, sizeof(KeyPoint) * npoints, cudaMemcpyDeviceToHost, stream)" 
CUDA error at /data/git/miner-tx1/catkin_ws/src/orb_slam_gpu/src/cuda/Fast_gpu.cu:507 code=46(cudaErrorDevicesUnavailable) "cudaMemcpyAsync(_keypoints, keypoints, sizeof(KeyPoint) * npoints, cudaMemcpyDeviceToHost, stream)" 
Segmentation fault
`
I attached the log file: [cuda_error.txt](https://github.com/yunchih/ORB-SLAM2-GPU2016-final/files/941252/cuda_error.txt)
I am running on TX1 with Jetpack 3
I had to rebuild the OpenCV to include the cuda support as per this instructions: [http://qiita.com/kendemu/items/a805b0b9828b6f6031db](http://qiita.com/kendemu/items/a805b0b9828b6f6031db)
The current ros_kinetic_opencv3 is based on opencv 3.2.0 so I did not have to use the patches mentioned in the instructions.
The Jetpack 3 comes with cuda 8.0 

To get it building I had to modify the following files:
 CmakeList.txt to add the OpenCV include dirs otherwise the cuda headers will not be found.
Thirdparty/g2o/g2o/solvers/linear_solver_eigen.h to remove one of the arguments, I think it is part of Eigen3 changes.
Here is the diff: [orb_slam_gpu.patch.txt](https://github.com/yunchih/ORB-SLAM2-GPU2016-final/files/941371/orb_slam_gpu.patch.txt)

Can you please help?

**Comment by yunchih** [comment]
An error of `cudaErrorDevicesUnavailable` sounds like environment  problem for me.  Are you able to run other Cuda problem on this TX1?  Are there other Cuda program running simultaneously?

**Comment by maciejmatuszak** [comment]
To isolate the problem I flashed the TX1 from scratch, build OpenCV and Pangolin no ROS at all. I tried OpenCV 3.2.0 and 3.1.0 but still the same problem. 
I am using customized kernel with NVMe driver. I will try to run all from MMC and with original kernel. 

I tried  couple of the cuda samples and those work ok.

Did you try it with latest Jetpack 3, CUDA 8.0 and OpenCV 3.2.0 ?

**Comment by silverneko** [comment]
No, we didn't try with Jetpack3. Since Jetpack3 was not released at the time we develop this project, we only tested with CUDA 7 / OpenCV 3.0 for TX1 and CUDA 8 RC / OpenCV 3.0 for PC. I suspect there might be some changes on TX1's kernel or CUDA runtime (we only have the kernel with 32bit user space back then). I'll look into this issue when I have time.

**Comment by silverneko** [comment]
I suspect that this may be a bug in our implementation related to this
https://github.com/yunchih/ORB-SLAM2-GPU2016-final/blob/master/src/ORBextractor.cc#L735

There was the bug which is if IC_Angel's asynchronous launch and join are in different loop iterations, then error would occur. I didn't fully identify the bug back then and somehow if the launch and join were in the same loop iteration the error disappears... very strange.
That said, even I am not able to reproduce that bug now (probably due to me using a different PC), nor can I reproduce your bug. Can you try to reproduce your bug with something like cuda-memcheck?

**Comment by maciejmatuszak** [comment]
To make more reproducible I run it with clean TX1. Just flashed the Jetpack3 without opencv, then build the Pangolin and Opencv. Still the same problem. 
One thing I notice is when I build it with CUDA -g -G flags and debug mode (CMAKE_BUILD_TYPE=DEBUG) then it will rum quite happy but very slow, (1 key frame in minutes). 

Attached is log from cuda-memcheck, not sure how helpful it will be since I can see only references to library paths and not ORB_SLAM code, I was expecting the NVCC -G -g flags would enable bit more info but I do not know much about cuda toolset.
There are 3 sessions in the logs, first two without cuda-memcheck and last with cuda-memcheck. 
Without cuda-memcheck it will return with error after 1'st or 2'nd key frame (GUI window bottom shows the KFs).
With cuda-memcheck I can observe the KF=3 or some times 5 but after that the whole desktop environment is frozen. I can kill the process from remote terminal and the desktop will unfreeze. 
[cuda-memcheck.txt](https://github.com/yunchih/ORB-SLAM2-GPU2016-final/files/950518/cuda-memcheck.txt)
If I can help in resolving the problem in any way please help, I am keen to get it working.

**Comment by silverneko** [comment]
From your attachment it looks like the crash originates from openCV's Gaussian filter. I suspect that openCV's gpu filter is not thread safe, since only the `kitti_stereo` triggers this bug but not monocular. I also found this bug report that I think is related: https://github.com/opencv/opencv/issues/6742

Try replacing the threaded execution of the two ORBExtractor in Frame::Frame() to sequential execution and see if the bug still triggers.
https://github.com/yunchih/ORB-SLAM2-GPU2016-final/blob/master/src/Frame.cc#L80
If the bug appears to be fixed, then I think we'll need to patch openCV's Gaussian filter to be thread safe or write our own Gaussian filter.

**Comment by maciejmatuszak** [comment]
Bulls eye!
I run the mono kity and there is no problem.
I modify then the threads calls to put the join in between forcing the second to wait until first finishes. Went trough kitti 00 sequence to the very end with about 0.3sec per frame.
I am rebuilding the OpenCV with the patch to use global memory. Should get better than 0.3sec per frame.
Once finished I will report back.
Thank you for your timely response!

Maciej

**Comment by silverneko** [comment]
If this is really some multithread issue, beware that these hacky code may or may not cause problems
https://github.com/yunchih/ORB-SLAM2-GPU2016-final/blob/master/src/ORBextractor.cc#L696
https://github.com/yunchih/ORB-SLAM2-GPU2016-final/blob/master/src/ORBextractor.cc#L839
these two static vars may better be managed & initialized by its residing thread.
Maybe make them member variables and initialize them here
https://github.com/yunchih/ORB-SLAM2-GPU2016-final/blob/master/src/ORBextractor.cc#L824

Really sorry for the hacky codes as me only focused on monocular tracking.
Even more sorry that I cannot fix it myself since I can't reproduce.

**Comment by maciejmatuszak** [comment]
I will look into the static variables. 
I tried to build it with just __global__ change but it looks like the variable is used within __device__ function and compilation fail. Looks like there was some changes after 3.2.0 where the patch was developed. I will look closer into this tomorrow. Today is holiday here and I do not want to get into trouble with the BOSS ;)
No need to apologize, I spend lot of time reviewing code in ops critical devices. I am of a opinion that one can write about 3 line of code without bug, especially in low level language as c. It takes team effort and extensive testing to iron them out. That's what github community is for :)
Maciej

**Comment by griz1112** [comment]
I built it successfully on the TX2 with Jetpack 3. However on the TX2 you have the newer kernel.  I built opencv 3.2.0 using this recipe.
http://docs.opencv.org/3.2.0/d6/d15/tutorial_building_tegra_cuda.html The only change I made was to drop the patches and change the CUDA_ARCH_BIN to 6.2 for the TX2. It runs great on the TX2 I'm using remode on the backend. I built it on the TX1 on the old jetpack but haven't tried with the new one yet. https://youtu.be/yBH9man45z0

**Comment by griz1112** [comment]
It also builds and runs on the Joule.

**Comment by maciejmatuszak** [comment]
Dann, did you tried the stereo kitti example?

**Comment by griz1112** [comment]
I used bag files for all my tests since I’m working with ROS.

**Comment by maciejmatuszak** [comment]
Hmm,
I tried to replicate it on laptop without success. It runs just fine, same version of opencv and cuda.
Not sure if the problem with constant memory is exactly the actual/only fault...

**Comment by silverneko** [comment]
Yeah, thread safety and timing issues are complicated. It is very possible that the issue exist on a devboard but not on a PC, as the processor architecture, libc/libc++ implementation, GPU's relative speed to CPU is different. Well, I think the problem we are having now is something with the multi-threaded execution of openCV or CUDA. The harder path is to try and patch openCV. The easier way is to just change [this two ORBExtractor call][1] from concurrent to sequence call. Perhaps TX1's CPU isn't powerful enough to gain improvement from multi-threaded ORBExtractor anyway, so I guess you can just go the easy solution.

[1]: https://github.com/yunchih/ORB-SLAM2-GPU2016-final/blob/master/src/Frame.cc#L80

**Comment by maciejmatuszak** [comment]
silverenko, with the patch I submitted the stereo works fine with concurrent threads.
I just fried the TX1 carrier board and zed camera, not sure if TX1 survived it... I am waiting for new zed and TX2 and carrier board. It should give bit more umpf...

**Comment by griz1112** [comment]
They sent me a new zed I was working with it the other night and the 
power dipped here. Zapped that sucker again. Only had it a couple of 
weeks. Have you checked out cartographer?


Dan

**Comment by maciejmatuszak** [comment]
Bugger... The ZED seems so sensitive to voltage spikes it is not funny for the price they charge for it. I did not play with cartographr yet. I want to try VINS-MEAN FIRST.
